/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { ProjectListRelationFilter } from "../../project/base/ProjectListRelationFilter";
import { EnvironmentListRelationFilter } from "../../environment/base/EnvironmentListRelationFilter";
import { SnapshotListRelationFilter } from "../../snapshot/base/SnapshotListRelationFilter";
import { StateListRelationFilter } from "../../state/base/StateListRelationFilter";

@InputType()
class UserWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  firstName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  lastName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  username?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ProjectListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ProjectListRelationFilter)
  @IsOptional()
  @Field(() => ProjectListRelationFilter, {
    nullable: true,
  })
  projects?: ProjectListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => EnvironmentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => EnvironmentListRelationFilter)
  @IsOptional()
  @Field(() => EnvironmentListRelationFilter, {
    nullable: true,
  })
  environments?: EnvironmentListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => SnapshotListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SnapshotListRelationFilter)
  @IsOptional()
  @Field(() => SnapshotListRelationFilter, {
    nullable: true,
  })
  snapshots?: SnapshotListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => StateListRelationFilter,
  })
  @ValidateNested()
  @Type(() => StateListRelationFilter)
  @IsOptional()
  @Field(() => StateListRelationFilter, {
    nullable: true,
  })
  states?: StateListRelationFilter;
}

export { UserWhereInput as UserWhereInput };
