/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Environment } from "./Environment";
import { EnvironmentCountArgs } from "./EnvironmentCountArgs";
import { EnvironmentFindManyArgs } from "./EnvironmentFindManyArgs";
import { EnvironmentFindUniqueArgs } from "./EnvironmentFindUniqueArgs";
import { CreateEnvironmentArgs } from "./CreateEnvironmentArgs";
import { UpdateEnvironmentArgs } from "./UpdateEnvironmentArgs";
import { DeleteEnvironmentArgs } from "./DeleteEnvironmentArgs";
import { SnapshotFindManyArgs } from "../../snapshot/base/SnapshotFindManyArgs";
import { Snapshot } from "../../snapshot/base/Snapshot";
import { StateFindManyArgs } from "../../state/base/StateFindManyArgs";
import { State } from "../../state/base/State";
import { User } from "../../user/base/User";
import { Project } from "../../project/base/Project";
import { EnvironmentService } from "../environment.service";
@graphql.Resolver(() => Environment)
export class EnvironmentResolverBase {
  constructor(protected readonly service: EnvironmentService) {}

  async _environmentsMeta(
    @graphql.Args() args: EnvironmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Environment])
  async environments(
    @graphql.Args() args: EnvironmentFindManyArgs
  ): Promise<Environment[]> {
    return this.service.environments(args);
  }

  @graphql.Query(() => Environment, { nullable: true })
  async environment(
    @graphql.Args() args: EnvironmentFindUniqueArgs
  ): Promise<Environment | null> {
    const result = await this.service.environment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Environment)
  async createEnvironment(
    @graphql.Args() args: CreateEnvironmentArgs
  ): Promise<Environment> {
    return await this.service.createEnvironment({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,

        project: args.data.project
          ? {
              connect: args.data.project,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Environment)
  async updateEnvironment(
    @graphql.Args() args: UpdateEnvironmentArgs
  ): Promise<Environment | null> {
    try {
      return await this.service.updateEnvironment({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,

          project: args.data.project
            ? {
                connect: args.data.project,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Environment)
  async deleteEnvironment(
    @graphql.Args() args: DeleteEnvironmentArgs
  ): Promise<Environment | null> {
    try {
      return await this.service.deleteEnvironment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Snapshot], { name: "snapshots" })
  async findSnapshots(
    @graphql.Parent() parent: Environment,
    @graphql.Args() args: SnapshotFindManyArgs
  ): Promise<Snapshot[]> {
    const results = await this.service.findSnapshots(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [State], { name: "states" })
  async findStates(
    @graphql.Parent() parent: Environment,
    @graphql.Args() args: StateFindManyArgs
  ): Promise<State[]> {
    const results = await this.service.findStates(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Environment): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Project, {
    nullable: true,
    name: "project",
  })
  async getProject(
    @graphql.Parent() parent: Environment
  ): Promise<Project | null> {
    const result = await this.service.getProject(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
