/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { TeamWhereUniqueInput } from "../../team/base/TeamWhereUniqueInput";
import { EnvironmentListRelationFilter } from "../../environment/base/EnvironmentListRelationFilter";
import { StateListRelationFilter } from "../../state/base/StateListRelationFilter";

@InputType()
class ProjectWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => TeamWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TeamWhereUniqueInput)
  @IsOptional()
  @Field(() => TeamWhereUniqueInput, {
    nullable: true,
  })
  team?: TeamWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => EnvironmentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => EnvironmentListRelationFilter)
  @IsOptional()
  @Field(() => EnvironmentListRelationFilter, {
    nullable: true,
  })
  environments?: EnvironmentListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => StateListRelationFilter,
  })
  @ValidateNested()
  @Type(() => StateListRelationFilter)
  @IsOptional()
  @Field(() => StateListRelationFilter, {
    nullable: true,
  })
  states?: StateListRelationFilter;
}

export { ProjectWhereInput as ProjectWhereInput };
