/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { Type } from "class-transformer";
import { TeamWhereUniqueInput } from "../../team/base/TeamWhereUniqueInput";
import { EnvironmentCreateNestedManyWithoutProjectsInput } from "./EnvironmentCreateNestedManyWithoutProjectsInput";
import { StateCreateNestedManyWithoutProjectsInput } from "./StateCreateNestedManyWithoutProjectsInput";

@InputType()
class ProjectCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TeamWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TeamWhereUniqueInput)
  @IsOptional()
  @Field(() => TeamWhereUniqueInput, {
    nullable: true,
  })
  team?: TeamWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => EnvironmentCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => EnvironmentCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => EnvironmentCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  environments?: EnvironmentCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: () => StateCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => StateCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => StateCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  states?: StateCreateNestedManyWithoutProjectsInput;
}

export { ProjectCreateInput as ProjectCreateInput };
